# -*- coding: utf-8 -*-
"""FunBasics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aTO8TGy6ZfpBb_jBcGHJ1gCQxyWe1xNj
"""

from matplotlib import pyplot as plt
import numpy as np

x=np.arange(1,10,0.1)
y=2*x+5

plt.plot(x,y)
plt.show()

x=np.arange(1,10,0.1)
y=2*x+5
plt.plot(x,y,color='r')
plt.title('Line plot')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.show()

x=np.arange(1,10,0.1)
y1=2*x+5
y2=3*x+10
plt.subplot(1,2,1)
plt.plot(x,y1)
plt.subplot(1,2,2)
plt.plot(x,y2)

# bar-plot
fruit={'apple':30,'mango':60,'banana':10}
names=list(fruit.keys())
quantity = list(fruit.values())

names,quantity

plt.bar(names,quantity)
plt.show()

# customizing bar plot
plt.bar(names,quantity,color='orange')
plt.title('Distribution of fruits')
plt.xlabel('Fruits')
plt.ylabel('quantity')
plt.show()

#scatter plot
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

plt.scatter(x, y)
plt.show()

#histogram
data=[1,2,3,1,4,7,8,9,6,5,4]
plt.hist(data)
plt.show()

import pandas as pd
iris=pd.read_csv('/content/Salaries.csv')
iris.head()

plt.hist(iris['rank'],color='red',bins=50)

#boxplot
one=[1,2,3,4,5,6,7,8]
two=[1,2,3,4,5,6,5,1]
three=[6,7,8,9,8,9,6,9]
data=list([one,two,three])
plt.boxplot(data)
plt.show()

#violin-plot
one=[1,2,3,4,5,6,7,8]
two=[1,2,3,4,5,6,5,1]
three=[6,7,8,9,8,9,6,9]
data=list([one,two,three])

plt.violinplot(data,showmedians=True,showmeans=True)
plt.grid(True)
plt.show()

#pie chart
fruits=['apple','mango','orange','grapes']
quantity=[30,40,50,60]
plt.pie(quantity,labels=fruits,autopct='%0.1f%%',shadow=True,explode=(0,0,0,0.10))
plt.show()

#doughnut chart
fruits=['apple','mango','orange','grapes']
quantity=[30,40,50,60]
pie1=plt.pie(quantity,labels=fruits,autopct='%0.1f%%',radius=2)
pie2=plt.pie([5],colors='white',radius=1)
plt.show()

#area-plot
x=[10,20,30,40,50,60,70,80,90]
y=[1,1,2,5,6,4,7,4,6,]

plt.stackplot(x,y)
plt.show()

