# -*- coding: utf-8 -*-
"""Salaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uqq9soGLXveXqzwnru-H7SzrTn2TQHAg
"""

import numpy as np
import pandas as pd

df=pd.read_csv('Salaries.csv')
print(df)

df.shape

df.head()

df.head(10)

df.tail()

df['salary'].dtype

df.columns

df.dtypes

df.columns

df['rank'].dtype

df.describe()

df['salary'].describe()

